server:
  port: 8084

spring:
  profiles:
    active: dev
  application:
    name: notification-service
  messages:
    basename: lang/messages
  freemarker:
    template-loader-path: classpath:/templates/
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: smtp.gmail.com
    port: 587
    username: global.lanzendorf.technologies@gmail.com
    password: mpsiyliixfxiciyh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

#Eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


logging:
  level:
    org.springframework.boot.context.config: DEBUG