server:
  port: 8084
spring:
  application:
    name: notification-service
  messages:
    basename: lang/messages
  cloud:
    kubernetes:
      discovery:
        enabled: true
  freemarker:
    template-loader-path: classpath:/templates/
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: kafka-service.kafka.svc.cluster.local:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
    producer:
      retries: 3

#Eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false
